config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "messages#index"
  resources :messages do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  #  [:edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :message

  validates :text, presence: true, length: {maximum: 30}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments

  validates :title, presence: true
  validates :name, presence: true
  validates :text, presence: true, length: {maximum: 200}

  mount_uploader :image, ImageUploader

  def self.search(title)
    if title != ""
      Message.where('title LIKE(?)', "%#{title}%")
    else
      Message.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    if  @comment.save
      respond_to do |format|
        format.html { redirect_to message_path(params[:message_id]) } 
        format.json
      end
    else
      flash.now[:alert] = 'コメントを入力してください。'
      render :show
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, message_id: params[:message_id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_message, only: [:edit, :show,]

  def index
    @messages = Message.includes(:user).order("created_at DESC")
  end
  

  def new
    @message = Message.new
  end
  
  def create
    @message = Message.create(message_params)
    @message.user = current_user
    if @message.save
      redirect_to messages_path, notice: 'メッセージが送信されました'
    else
      flash.now[:alert] = 'メッセージの未入力または文字数制限です。'
      render :new
    end
  end
  
  def destroy
    message = Message.find(params[:id])
    if message.destroy
      redirect_to messages_path, notice: 'メッセージが削除されました'
    end    
  end
  
  def edit
  end
  
  def show
    @comment = Comment.new
    @comments = @message.comments.includes(:user)
  end
  
  def update
    @message = Message.find(params[:id])
    if @message.update(message_params)
      redirect_to messages_path, notice: 'メッセージが編集されました'
    else
      flash.now[:alert] = 'メッセージの未入力または文字数制限です。'
      render :edit
    end
  end
  
  def search
    @messages = Message.search(params[:title_key])
  end

  private
  def message_params
    params.require(:message).permit(:title, :name, :text).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def set_message
    @message = Message.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # def edit
  # end

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @messages = user.messages
  end
  
  # def update
  #   if current_user.update(user_params)
  #     redirect_to root_path
  #   else
  #     render :edit
  #   end
  # end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BookTalk
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    %header.header
      .header__bar.row
        %h1.grid-6
          %a.title{:href => "/"} BookTalk
        - if user_signed_in?
          .user_nav.grid-6
            %sapn.post_user
              = current_user.nickname
              %ul.user__info
                %li
                  = link_to "マイページ", user_path(current_user)
                %li
                  = link_to "ログアウト", destroy_user_session_path, method: :delete
            = link_to "投稿する", new_message_path, class: "post"
        - else
          .user_nav.grid-6
            = link_to "ログイン", new_user_session_path, class: "post"
            = link_to "新規登録", new_user_registration_path, class: "post"
    = render 'layouts/notifications'
    = yield
    %footer
      %p.footer
        BookTalk 2020.

app/views/messages/_message.html.haml
.contents__post 
  .message_title 
    = message.title
  .message_name
    = message.name
  .message_text 
    = message.text
  .message_nickname
    = link_to user_path(message.user.id), class: "user_nickname" do
      nickname : 
      = message.user.nickname 
  .btn 
    = link_to message_path(message) do
      = icon('fas', 'cog', class: "btn_icon")

app/views/messages/edit.html.haml
.contents
  .contents__form
    = form_with model: @message, html: {class: "form_box"}, local: true do |f|
      .form_field
        = f.text_field :title, class: "message_title", placeholder: "tiile" 
        = f.text_field :name, class: "message_name", placeholder: "name(著者)" 
        = f.text_area :text, class: "message_text", placeholder: "type a message"
        .message_nickname 
          nickname : 
          = @message.user.nickname 
      .form_submit
        = f.submit 'Send', class: "submit"

app/views/messages/index.html.haml
.contents
  .search_box
    = form_with url: search_messages_path, method: :get, class: "search_form", local: true do |f|
      = f.text_field :title_key, placeholder: "本のタイトルを検索する", class: "search_input"
      = f.submit '検索', class: "search_btn"

  .contents_list
    = render @messages
  -# - @messages.each do |message|
    -# = render partial: "message", locals: { message: message}
    -# .contents__post 
    -#   .message_title 
    -#     = message.title
    -#   .message_name
    -#     = message.name
    -#   .message_text 
    -#     = message.text
    -#   .message_nickname
    -#     = link_to user_path(message.user.id), class: "user_nickname" do
    -#       nickname : 
    -#       = message.user.nickname 
    -#   .btn 
    -#     = link_to message_path(message) do
    -#       Show
    -#       -# = icon('fas', 'cog', class: "btn_icon")

app/views/messages/new.html.haml
.contents
  .contents__form
    = form_with model: @message, html: {class: "form_box"}, local: true do |f|
      .form_field
        = f.text_field :title, class: "message_title", placeholder: "tiile" 
        = f.text_field :name, class: "message_name", placeholder: "name(著者)" 
        = f.text_area :text, class: "message_text", placeholder: "type a message"
        .message_nickname
          nickname : 
          = current_user.nickname
      .form_submit
        = f.submit 'Send', class: "submit"

app/views/messages/search.html.haml
.contents
  .search_box
    = form_with url: search_messages_path, method: :get, class: "search_form", local: true do |f|
      = f.text_field :title_key, placeholder: "本のタイトルを検索する", class: "search_input"
      = f.submit '検索', class: "search_btn"
  .contents_row
    - @messages.each do |message|
      = render partial: "message", locals: { message: message}

app/views/messages/show.html.haml
.contents
  .content_message
    .contents__post
      .message_title 
        = @message.title
      .message_name
        = @message.name
      .message_text 
        = @message.text
      .message_nickname
        nickname : 
        = @message.user.nickname
      .btn
        %ul.list
          - if user_signed_in? && current_user.id == @message.user_id
            %li
              = link_to edit_message_path(@message.id), method: :get do
                Edit
            %li
              = link_to message_path(@message.id), method: :delete do
                delete
  .contents_form
    -if current_user
      = form_with model: [@message, @comment],id: "new_comment", local: true do |f|
        .form_field
          = f.text_area :text, class: "comment_text", placeholder: "type a comment"
        .form_submit
          = f.submit 'Send', class: "submit"
    - else
      %strong
        %p.no_user_comment 
          *** コメントの投稿には新規登録/ログインが必要です ***
  .comments 
    <コメント一覧>
    - if @comments
      - @comments.each do |comment|
        %ul
          %li.comment_user
            %strong
              = link_to comment.user.nickname, user_path(comment.user_id), class: "comment_user" 
          %li.comment_message
            *
            = comment.text

app/views/users/show.html.haml
.contents
  .contents__user
    = @nickname
    さんの投稿一覧
  .content_message
    - @messages.each do |message|
      = render partial: "messages/message", locals: { message: message}
      -# .contents__post 
      -#   .message_title 
      -#     = message.title
      -#   .message_name
      -#     = message.name
      -#   .message_text 
      -#     = message.text
      -#   .btn 
      -#     = link_to message_path(message) do
      -#       Show

app/views/users/test.html.haml
.test 
  .test_message これはテストです。